services:
  api:
    container_name: marketplace_api
    build:
      context: ./deploy/php/
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    #      - ./deploy/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    #      - ./deploy/php/crontab:/etc/crontabs/root
    networks:
      - marketplace

  nginx:
    container_name: marketplace_nginx
    build:
      context: ./deploy/nginx
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www:rw
    depends_on:
      - api
    networks:
      - marketplace

  db:
    container_name: marketplace_db
    build:
      context: ./deploy/db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./deploy/db/data:/var/lib/postgresql/data
    networks:
      - marketplace

networks:
  marketplace:
    driver: bridge
